version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: programacion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MB35mESjUg7B@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    ports:
      - "8010:8010"
    environment:
      DATABASE_URL: postgresql://postgres:zJmO99T7siPFYb5BnMy9Ixrhn0UJZZo6hoHJjSmtSCa15T12hMJJ7bJ3Rdx0Nv5B@38.242.137.70:5432/postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
